---
title: "PolarWatch Metadata Information Page"
---

The PolarWatch Metadata Information Page is designed to provide comprehensive metadata-related information on the data products distributed by PolarWatch, emphasizing adherence to FAIRS and Open Data principles. 

Furthermore, it aims to facilitate both current and future data product distributions through the PolarWatch data server by offering detailed metadata guidelines and recommendations.

### For Data Users

On the __Data List__ page, users can access a variety of resources, including:

* __Data Change Logs:__  Provides updates on any modifications to data products, such as variable adjustments or corrections to missing dates.
* __AI-Ready Checklist__: Delivers metadata specifications for AI-ready open environmental data, ensuring readiness for artificial intelligence applications.
* __Data/Server Availability__: Supplies notifications regarding the availability of data or server access, keeping users informed of operational status.

### For Data Developers

Guidelines and recommendations can be found on the __Guidelines__ page:

* __PolarWatch Metadata Recommendations:__ These guidelines are designed for data products hosted on the PolarWatch ERDDAP Server, outlining metadata attributes and descriptions in accordance with established industry convention standards, as noted in the Standard column.

* __AI-Ready Checklist Guidelines:__ Presents a set of guidelines and recommendations for crafting metadata that meets the criteria for AI-ready open environmental data. This document mirrors [the latest version available from the source repository](https://github.com/ESIPFed/data-readiness/blob/main/checklist-published/ai-ready-data-checklist-v.1.0.md)., ensuring users have access to the most current standards.
 


