
# Data Management: <br/> nesdis_blendednesdis_ease2_latlon_nhem_1k,  nesdis_ease2_latlon_shem_1k
> Updated Apr 18, 2024


## Data Description 
This dataset includes latitude and longitude grids that correspond 
to the Y-grid and X-grid used in the NESDIS sea ice products in the Arctic and Antarctic.

Presented in the EASE-2 (Equal-Area Scalable Earth-2) projection at a 1km resolution, 
this dataset serves as ancillary data to the sea ice data products (nesdis_blendedsic_nhem_daily, nesdis_blendedsic_shem_daily) 
in the same projection: 

| Ancillary data identifier    | Remote sensing data identifier|
| -------- | ------- |
| nesdis_blendednesdis_ease2_latlon_nhem_1k  | nesdis_blendedsic_nhem_daily    |
| nesdis_blendednesdis_ease2_latlon_shem_1k | nesdis_blendedsic_shem_daily     |
: {.striped .hover .auto_width .to_center}


_* data identifiers are unique data ids used on the PolarWatch ERDDAP data server_  


The file sizes for the Arctic and Antarctic data files are approximately 490MB and 395MB, 
respectively. These files can be downloaded from the PolarWatch ERDDAP server.


* Arctic file download : [https://polarwatch.noaa.gov/erddap/files/nesdis_ease2_latlon_nhem_1k/](https://polarwatch.noaa.gov/erddap/files/nesdis_ease2_latlon_nhem_1k/)
* Antarctic file download : [https://polarwatch.noaa.gov/erddap/files/nesdis_ease2_latlon_shem_1k/](https://polarwatch.noaa.gov/erddap/files/nesdis_ease2_latlon_shem_1k/)



## Process Description

The data files were developed by NESDIS in collaboration with the University 
of Wisconsin and provided to PolarWatch. Additional projection metadata 
attributes were added to the files, and 
they were compressed for efficient distribution.

```{mermaid}
flowchart LR
  A(File on FTP Server) -->B(File Download to PolarWatch)
  B --> C(Metadata added to files, Compressed, Stored)
  C --> D(Accessible on ERDDAP)
```


## Metadata

PolarWatch provides extensive metadata on ERDDAP in addition to embedded metadata in NetCDF.  PolarWatch added additional crs (coordinate reference system) attributes to be machine 
readable by widely used software. The additional attributes are ```srid```, ```proj4text```, ```spatial_ref```. 

The metadata standard used is CF-16, and both ERDDAP metadata and NetCDF metadata are machine readable.  


__Additional crs attributes added to files__

```
# for northern hemisphere file (arctic)
    crs:srid = "EPSG:6931" ;
    crs:proj4text = "+proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs"
    crs:spatial_ref = "PROJCS[\"WGS 84 / NSIDC EASE-Grid 2.0 North\",GEOGCS[\"WGS 84\",
      DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY
      [\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",
      0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY
      [\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],
      PARAMETER[\"latitude_of_center\",90],PARAMETER[\"longitude_of_center\",0],
      PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],
      UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AUTHORITY[\"EPSG\",\"6931\"]]" ;


# For southern hemisphere file (antarctic)
    crs:srid = "EPSG:6932" ;
    crs:proj4text = "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs"
    crs:spatial_ref = PROJCS[\"WGS 84 / NSIDC EASE-Grid 2.0 South\",
    GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,
    AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],
    PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],
    UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],
    AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],
    PARAMETER[\"latitude_of_center\",-90],PARAMETER[\"longitude_of_center\",0],
    PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],
    UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AUTHORITY[\"EPSG\",\"6932\"]]

```

__ERDDAP metadata links__

* Arctic: https://polarwatch.noaa.gov/erddap/info/nesdis_ease2_latlon_nhem_1k/index.html
* Antarctic: https://polarwatch.noaa.gov/erddap/info/nesdis_ease2_latlon_shem_1k/index.html


## Storage and Backup
Data are stored in directory on the PolarWatch data server and ERDDAP points to the directory. 
In the case of the event of an accident, the recovery will be handled by PolarWatch team. 


## Policies for Access and Sharing
Data are publically accessible. Please use [NCEI Data Licensing](https://www.ncei.noaa.gov/archive#:~:text=Because%20works%20of%20the%20US%20government%20are,license%20to%20that%20portion%20of%20its%20holdings.)
.   ERDDAP is the primary data distribution system with a web interface.  

Data can be searched and accessed: 

* [PolarWatch Catalog](https://polarwatch.noaa.gov/catalog/) or [PolarWatch ERDDAP Web Interface](https://polarwatch.noaa.gov/erddap/)
* [ERDDAP RESTful web services](https://polarwatch.noaa.gov/erddap/rest.html) for software to access data.
* [Tutorials and code samples](https://github.com/coastwatch-training/CoastWatch-Tutorials) are available to access data and metadata in commonly used languages (i.e. R, Python)
* Contact PolarWatch Operatins Manager at polar.watch@noaa.gov


## Plans for archiving data

PolarWatch collaborates with data developers to manage and distribute both actively updated datasets and those that have become deprecated. While ensuring continued access to these varied datasets, it's important to note that PolarWatch does not serve as an archive for data.


## Roles and Responsibilities

* The PolarWatch Operations Manager is tasked with the implementation, documentation, and periodic updating of the Data Management Plan.
* The data workflow is designed to be automated. This process is closely monitored, with automatic notifications being sent out in the event of any errors. 
* The documentation for internal data processing is accessible internally, ensuring that relevant team members can access it as needed. Additionally, all scripts associated with this processing are stored in a private repository.

